// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: fl/fl.proto

package flpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrainRequest asks a Worker to train locally on the partition at
// dataset_partition_path for the given FL round. The path must be reachable
// from the Worker's own filesystem (e.g. a shared volume in docker-compose).
type TrainRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RoundId              int64                  `protobuf:"varint,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	DatasetPartitionPath string                 `protobuf:"bytes,2,opt,name=dataset_partition_path,json=datasetPartitionPath,proto3" json:"dataset_partition_path,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_fl_fl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fl_fl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_fl_fl_proto_rawDescGZIP(), []int{0}
}

func (x *TrainRequest) GetRoundId() int64 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *TrainRequest) GetDatasetPartitionPath() string {
	if x != nil {
		return x.DatasetPartitionPath
	}
	return ""
}

// WordCounts is a wrapper around a flat word->count map, needed because
// proto3 does not allow a map value to itself be a map.
type WordCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        map[string]int64       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordCounts) Reset() {
	*x = WordCounts{}
	mi := &file_fl_fl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordCounts) ProtoMessage() {}

func (x *WordCounts) ProtoReflect() protoreflect.Message {
	mi := &file_fl_fl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordCounts.ProtoReflect.Descriptor instead.
func (*WordCounts) Descriptor() ([]byte, []int) {
	return file_fl_fl_proto_rawDescGZIP(), []int{1}
}

func (x *WordCounts) GetCounts() map[string]int64 {
	if x != nil {
		return x.Counts
	}
	return nil
}

// LocalModelUpdate carries a Worker's local word/class counts to the
// Aggregator. Raw messages never leave the Worker.
type LocalModelUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       int64                  `protobuf:"varint,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WordCounts    map[string]*WordCounts `protobuf:"bytes,3,rep,name=word_counts,json=wordCounts,proto3" json:"word_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClassTotals   map[string]int64       `protobuf:"bytes,4,rep,name=class_totals,json=classTotals,proto3" json:"class_totals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalModelUpdate) Reset() {
	*x = LocalModelUpdate{}
	mi := &file_fl_fl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalModelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalModelUpdate) ProtoMessage() {}

func (x *LocalModelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_fl_fl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalModelUpdate.ProtoReflect.Descriptor instead.
func (*LocalModelUpdate) Descriptor() ([]byte, []int) {
	return file_fl_fl_proto_rawDescGZIP(), []int{2}
}

func (x *LocalModelUpdate) GetRoundId() int64 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *LocalModelUpdate) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *LocalModelUpdate) GetWordCounts() map[string]*WordCounts {
	if x != nil {
		return x.WordCounts
	}
	return nil
}

func (x *LocalModelUpdate) GetClassTotals() map[string]int64 {
	if x != nil {
		return x.ClassTotals
	}
	return nil
}

// AggregateTrigger tells the Aggregator how many LocalModelUpdate messages to
// collect for round_id before producing an AggregatedModel.
type AggregateTrigger struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoundId         int64                  `protobuf:"varint,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	ExpectedWorkers int64                  `protobuf:"varint,2,opt,name=expected_workers,json=expectedWorkers,proto3" json:"expected_workers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AggregateTrigger) Reset() {
	*x = AggregateTrigger{}
	mi := &file_fl_fl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateTrigger) ProtoMessage() {}

func (x *AggregateTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_fl_fl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateTrigger.ProtoReflect.Descriptor instead.
func (*AggregateTrigger) Descriptor() ([]byte, []int) {
	return file_fl_fl_proto_rawDescGZIP(), []int{3}
}

func (x *AggregateTrigger) GetRoundId() int64 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *AggregateTrigger) GetExpectedWorkers() int64 {
	if x != nil {
		return x.ExpectedWorkers
	}
	return 0
}

// WordProbs is a wrapper around a flat word->probability map, for the same
// nested-map reason as WordCounts.
type WordProbs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Probs         map[string]float64     `protobuf:"bytes,1,rep,name=probs,proto3" json:"probs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordProbs) Reset() {
	*x = WordProbs{}
	mi := &file_fl_fl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordProbs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordProbs) ProtoMessage() {}

func (x *WordProbs) ProtoReflect() protoreflect.Message {
	mi := &file_fl_fl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordProbs.ProtoReflect.Descriptor instead.
func (*WordProbs) Descriptor() ([]byte, []int) {
	return file_fl_fl_proto_rawDescGZIP(), []int{4}
}

func (x *WordProbs) GetProbs() map[string]float64 {
	if x != nil {
		return x.Probs
	}
	return nil
}

// AggregatedModel carries the FedAvg-combined global model from the
// Aggregator back to the Coordinator for evaluation.
type AggregatedModel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoundId         int64                  `protobuf:"varint,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	GlobalWordProbs map[string]*WordProbs  `protobuf:"bytes,2,rep,name=global_word_probs,json=globalWordProbs,proto3" json:"global_word_probs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClassPriors     map[string]float64     `protobuf:"bytes,3,rep,name=class_priors,json=classPriors,proto3" json:"class_priors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AggregatedModel) Reset() {
	*x = AggregatedModel{}
	mi := &file_fl_fl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedModel) ProtoMessage() {}

func (x *AggregatedModel) ProtoReflect() protoreflect.Message {
	mi := &file_fl_fl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedModel.ProtoReflect.Descriptor instead.
func (*AggregatedModel) Descriptor() ([]byte, []int) {
	return file_fl_fl_proto_rawDescGZIP(), []int{5}
}

func (x *AggregatedModel) GetRoundId() int64 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *AggregatedModel) GetGlobalWordProbs() map[string]*WordProbs {
	if x != nil {
		return x.GlobalWordProbs
	}
	return nil
}

func (x *AggregatedModel) GetClassPriors() map[string]float64 {
	if x != nil {
		return x.ClassPriors
	}
	return nil
}

var File_fl_fl_proto protoreflect.FileDescriptor

const file_fl_fl_proto_rawDesc = "" +
	"\n" +
	"\vfl/fl.proto\x12\x04flpb\"_\n" +
	"\fTrainRequest\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\x03R\aroundId\x124\n" +
	"\x16dataset_partition_path\x18\x02 \x01(\tR\x14datasetPartitionPath\"}\n" +
	"\n" +
	"WordCounts\x124\n" +
	"\x06counts\x18\x01 \x03(\v2\x1c.flpb.WordCounts.CountsEntryR\x06counts\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xf0\x02\n" +
	"\x10LocalModelUpdate\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\x03R\aroundId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12G\n" +
	"\vword_counts\x18\x03 \x03(\v2&.flpb.LocalModelUpdate.WordCountsEntryR\n" +
	"wordCounts\x12J\n" +
	"\fclass_totals\x18\x04 \x03(\v2'.flpb.LocalModelUpdate.ClassTotalsEntryR\vclassTotals\x1aO\n" +
	"\x0fWordCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.flpb.WordCountsR\x05value:\x028\x01\x1a>\n" +
	"\x10ClassTotalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"X\n" +
	"\x10AggregateTrigger\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\x03R\aroundId\x12)\n" +
	"\x10expected_workers\x18\x02 \x01(\x03R\x0fexpectedWorkers\"w\n" +
	"\tWordProbs\x120\n" +
	"\x05probs\x18\x01 \x03(\v2\x1a.flpb.WordProbs.ProbsEntryR\x05probs\x1a8\n" +
	"\n" +
	"ProbsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xe4\x02\n" +
	"\x0fAggregatedModel\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\x03R\aroundId\x12V\n" +
	"\x11global_word_probs\x18\x02 \x03(\v2*.flpb.AggregatedModel.GlobalWordProbsEntryR\x0fglobalWordProbs\x12I\n" +
	"\fclass_priors\x18\x03 \x03(\v2&.flpb.AggregatedModel.ClassPriorsEntryR\vclassPriors\x1aS\n" +
	"\x14GlobalWordProbsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.flpb.WordProbsR\x05value:\x028\x01\x1a>\n" +
	"\x10ClassPriorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01BTZRgithub.com/zebi30/sms-spam-validation-with-custom-agent-framework/internal/fl/flpbb\x06proto3"

var (
	file_fl_fl_proto_rawDescOnce sync.Once
	file_fl_fl_proto_rawDescData []byte
)

func file_fl_fl_proto_rawDescGZIP() []byte {
	file_fl_fl_proto_rawDescOnce.Do(func() {
		file_fl_fl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fl_fl_proto_rawDesc), len(file_fl_fl_proto_rawDesc)))
	})
	return file_fl_fl_proto_rawDescData
}

var file_fl_fl_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_fl_fl_proto_goTypes = []any{
	(*TrainRequest)(nil),     // 0: flpb.TrainRequest
	(*WordCounts)(nil),       // 1: flpb.WordCounts
	(*LocalModelUpdate)(nil), // 2: flpb.LocalModelUpdate
	(*AggregateTrigger)(nil), // 3: flpb.AggregateTrigger
	(*WordProbs)(nil),        // 4: flpb.WordProbs
	(*AggregatedModel)(nil),  // 5: flpb.AggregatedModel
	nil,                      // 6: flpb.WordCounts.CountsEntry
	nil,                      // 7: flpb.LocalModelUpdate.WordCountsEntry
	nil,                      // 8: flpb.LocalModelUpdate.ClassTotalsEntry
	nil,                      // 9: flpb.WordProbs.ProbsEntry
	nil,                      // 10: flpb.AggregatedModel.GlobalWordProbsEntry
	nil,                      // 11: flpb.AggregatedModel.ClassPriorsEntry
}
var file_fl_fl_proto_depIdxs = []int32{
	6,  // 0: flpb.WordCounts.counts:type_name -> flpb.WordCounts.CountsEntry
	7,  // 1: flpb.LocalModelUpdate.word_counts:type_name -> flpb.LocalModelUpdate.WordCountsEntry
	8,  // 2: flpb.LocalModelUpdate.class_totals:type_name -> flpb.LocalModelUpdate.ClassTotalsEntry
	9,  // 3: flpb.WordProbs.probs:type_name -> flpb.WordProbs.ProbsEntry
	10, // 4: flpb.AggregatedModel.global_word_probs:type_name -> flpb.AggregatedModel.GlobalWordProbsEntry
	11, // 5: flpb.AggregatedModel.class_priors:type_name -> flpb.AggregatedModel.ClassPriorsEntry
	1,  // 6: flpb.LocalModelUpdate.WordCountsEntry.value:type_name -> flpb.WordCounts
	4,  // 7: flpb.AggregatedModel.GlobalWordProbsEntry.value:type_name -> flpb.WordProbs
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_fl_fl_proto_init() }
func file_fl_fl_proto_init() {
	if File_fl_fl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fl_fl_proto_rawDesc), len(file_fl_fl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fl_fl_proto_goTypes,
		DependencyIndexes: file_fl_fl_proto_depIdxs,
		MessageInfos:      file_fl_fl_proto_msgTypes,
	}.Build()
	File_fl_fl_proto = out.File
	file_fl_fl_proto_goTypes = nil
	file_fl_fl_proto_depIdxs = nil
}
