// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: actorremote/transport.proto

package remotepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope addresses a message to a specific actor on the receiving node.
// The payload is a well-known google.protobuf.Any so the transport stays
// generic: any proto.Message can be delivered without the framework needing
// to know its concrete type ahead of time.
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_actorremote_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_actorremote_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_actorremote_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Envelope) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Ack is an empty acknowledgement of a delivered Envelope.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_actorremote_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_actorremote_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_actorremote_transport_proto_rawDescGZIP(), []int{1}
}

var File_actorremote_transport_proto protoreflect.FileDescriptor

const file_actorremote_transport_proto_rawDesc = "" +
	"\n" +
	"\x1bactorremote/transport.proto\x12\vactorremote\x1a\x19google/protobuf/any.proto\"W\n" +
	"\bEnvelope\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x05\n" +
	"\x03Ack2<\n" +
	"\tTransport\x12/\n" +
	"\x04Send\x12\x15.actorremote.Envelope\x1a\x10.actorremote.AckB]Z[github.com/zebi30/sms-spam-validation-with-custom-agent-framework/pkg/actor/remote/remotepbb\x06proto3"

var (
	file_actorremote_transport_proto_rawDescOnce sync.Once
	file_actorremote_transport_proto_rawDescData []byte
)

func file_actorremote_transport_proto_rawDescGZIP() []byte {
	file_actorremote_transport_proto_rawDescOnce.Do(func() {
		file_actorremote_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actorremote_transport_proto_rawDesc), len(file_actorremote_transport_proto_rawDesc)))
	})
	return file_actorremote_transport_proto_rawDescData
}

var file_actorremote_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_actorremote_transport_proto_goTypes = []any{
	(*Envelope)(nil),  // 0: actorremote.Envelope
	(*Ack)(nil),       // 1: actorremote.Ack
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_actorremote_transport_proto_depIdxs = []int32{
	2, // 0: actorremote.Envelope.payload:type_name -> google.protobuf.Any
	0, // 1: actorremote.Transport.Send:input_type -> actorremote.Envelope
	1, // 2: actorremote.Transport.Send:output_type -> actorremote.Ack
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_actorremote_transport_proto_init() }
func file_actorremote_transport_proto_init() {
	if File_actorremote_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actorremote_transport_proto_rawDesc), len(file_actorremote_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_actorremote_transport_proto_goTypes,
		DependencyIndexes: file_actorremote_transport_proto_depIdxs,
		MessageInfos:      file_actorremote_transport_proto_msgTypes,
	}.Build()
	File_actorremote_transport_proto = out.File
	file_actorremote_transport_proto_goTypes = nil
	file_actorremote_transport_proto_depIdxs = nil
}
