// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: registry/registry.proto

package registrypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeJoin announces that node_id is now an active cluster member.
type NodeJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeJoin) Reset() {
	*x = NodeJoin{}
	mi := &file_registry_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeJoin) ProtoMessage() {}

func (x *NodeJoin) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeJoin.ProtoReflect.Descriptor instead.
func (*NodeJoin) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{0}
}

func (x *NodeJoin) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// NodeLeave announces that node_id has left the cluster.
type NodeLeave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLeave) Reset() {
	*x = NodeLeave{}
	mi := &file_registry_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLeave) ProtoMessage() {}

func (x *NodeLeave) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLeave.ProtoReflect.Descriptor instead.
func (*NodeLeave) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{1}
}

func (x *NodeLeave) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// RoundComplete tells the registry that node_id finished one more FL round.
type RoundComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundComplete) Reset() {
	*x = RoundComplete{}
	mi := &file_registry_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundComplete) ProtoMessage() {}

func (x *RoundComplete) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundComplete.ProtoReflect.Descriptor instead.
func (*RoundComplete) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RoundComplete) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// MergeRequest carries a peer registry's G-Counter snapshot so two replicas
// can converge via CRDT merge, over the wire, in either direction.
type MergeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Counter       map[string]int64       `protobuf:"bytes,2,rep,name=counter,proto3" json:"counter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MergeRequest) Reset() {
	*x = MergeRequest{}
	mi := &file_registry_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeRequest) ProtoMessage() {}

func (x *MergeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeRequest.ProtoReflect.Descriptor instead.
func (*MergeRequest) Descriptor() ([]byte, []int) {
	return file_registry_registry_proto_rawDescGZIP(), []int{3}
}

func (x *MergeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MergeRequest) GetCounter() map[string]int64 {
	if x != nil {
		return x.Counter
	}
	return nil
}

var File_registry_registry_proto protoreflect.FileDescriptor

const file_registry_registry_proto_rawDesc = "" +
	"\n" +
	"\x17registry/registry.proto\x12\n" +
	"registrypb\"#\n" +
	"\bNodeJoin\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"$\n" +
	"\tNodeLeave\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"(\n" +
	"\rRoundComplete\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xa4\x01\n" +
	"\fMergeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12?\n" +
	"\acounter\x18\x02 \x03(\v2%.registrypb.MergeRequest.CounterEntryR\acounter\x1a:\n" +
	"\fCounterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B`Z^github.com/zebi30/sms-spam-validation-with-custom-agent-framework/internal/registry/registrypbb\x06proto3"

var (
	file_registry_registry_proto_rawDescOnce sync.Once
	file_registry_registry_proto_rawDescData []byte
)

func file_registry_registry_proto_rawDescGZIP() []byte {
	file_registry_registry_proto_rawDescOnce.Do(func() {
		file_registry_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_registry_proto_rawDesc), len(file_registry_registry_proto_rawDesc)))
	})
	return file_registry_registry_proto_rawDescData
}

var file_registry_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_registry_registry_proto_goTypes = []any{
	(*NodeJoin)(nil),      // 0: registrypb.NodeJoin
	(*NodeLeave)(nil),     // 1: registrypb.NodeLeave
	(*RoundComplete)(nil), // 2: registrypb.RoundComplete
	(*MergeRequest)(nil),  // 3: registrypb.MergeRequest
	nil,                   // 4: registrypb.MergeRequest.CounterEntry
}
var file_registry_registry_proto_depIdxs = []int32{
	4, // 0: registrypb.MergeRequest.counter:type_name -> registrypb.MergeRequest.CounterEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_registry_registry_proto_init() }
func file_registry_registry_proto_init() {
	if File_registry_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_registry_proto_rawDesc), len(file_registry_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registry_registry_proto_goTypes,
		DependencyIndexes: file_registry_registry_proto_depIdxs,
		MessageInfos:      file_registry_registry_proto_msgTypes,
	}.Build()
	File_registry_registry_proto = out.File
	file_registry_registry_proto_goTypes = nil
	file_registry_registry_proto_depIdxs = nil
}
