// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: cluster/cluster.proto

package clusterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeerInfo identifies one cluster member and the address its
// actor-transport gRPC server (pkg/actor/remote) listens on.
type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_cluster_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// ReplyAddress tells a Provider node where to route an asynchronous reply:
// which actor-transport server to dial, and which local actor to address.
type ReplyAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyAddress) Reset() {
	*x = ReplyAddress{}
	mi := &file_cluster_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyAddress) ProtoMessage() {}

func (x *ReplyAddress) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyAddress.ProtoReflect.Descriptor instead.
func (*ReplyAddress) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyAddress) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *ReplyAddress) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

// JoinCluster registers self as an active member with the Provider node.
type JoinCluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Self          *PeerInfo              `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCluster) Reset() {
	*x = JoinCluster{}
	mi := &file_cluster_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCluster) ProtoMessage() {}

func (x *JoinCluster) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCluster.ProtoReflect.Descriptor instead.
func (*JoinCluster) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *JoinCluster) GetSelf() *PeerInfo {
	if x != nil {
		return x.Self
	}
	return nil
}

// LeaveCluster removes node_id from the Provider's active member list.
type LeaveCluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCluster) Reset() {
	*x = LeaveCluster{}
	mi := &file_cluster_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCluster) ProtoMessage() {}

func (x *LeaveCluster) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCluster.ProtoReflect.Descriptor instead.
func (*LeaveCluster) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveCluster) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// DiscoverPeers asks the Provider node for the current member list, to be
// delivered asynchronously as a PeerList sent to reply_to.
type DiscoverPeers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyTo       *ReplyAddress          `protobuf:"bytes,1,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverPeers) Reset() {
	*x = DiscoverPeers{}
	mi := &file_cluster_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverPeers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverPeers) ProtoMessage() {}

func (x *DiscoverPeers) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverPeers.ProtoReflect.Descriptor instead.
func (*DiscoverPeers) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverPeers) GetReplyTo() *ReplyAddress {
	if x != nil {
		return x.ReplyTo
	}
	return nil
}

// PeerList is the Provider's answer to JoinCluster or DiscoverPeers.
type PeerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerList) Reset() {
	*x = PeerList{}
	mi := &file_cluster_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerList) ProtoMessage() {}

func (x *PeerList) ProtoReflect() protoreflect.Message {
	mi := &file_cluster_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerList.ProtoReflect.Descriptor instead.
func (*PeerList) Descriptor() ([]byte, []int) {
	return file_cluster_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *PeerList) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

var File_cluster_cluster_proto protoreflect.FileDescriptor

const file_cluster_cluster_proto_rawDesc = "" +
	"\n" +
	"\x15cluster/cluster.proto\x12\tclusterpb\"7\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"=\n" +
	"\fReplyAddress\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\"6\n" +
	"\vJoinCluster\x12'\n" +
	"\x04self\x18\x01 \x01(\v2\x13.clusterpb.PeerInfoR\x04self\"'\n" +
	"\fLeaveCluster\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"C\n" +
	"\rDiscoverPeers\x122\n" +
	"\breply_to\x18\x01 \x01(\v2\x17.clusterpb.ReplyAddressR\areplyTo\"5\n" +
	"\bPeerList\x12)\n" +
	"\x05peers\x18\x01 \x03(\v2\x13.clusterpb.PeerInfoR\x05peersB^Z\\github.com/zebi30/sms-spam-validation-with-custom-agent-framework/internal/cluster/clusterpbb\x06proto3"

var (
	file_cluster_cluster_proto_rawDescOnce sync.Once
	file_cluster_cluster_proto_rawDescData []byte
)

func file_cluster_cluster_proto_rawDescGZIP() []byte {
	file_cluster_cluster_proto_rawDescOnce.Do(func() {
		file_cluster_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cluster_cluster_proto_rawDesc), len(file_cluster_cluster_proto_rawDesc)))
	})
	return file_cluster_cluster_proto_rawDescData
}

var file_cluster_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_cluster_cluster_proto_goTypes = []any{
	(*PeerInfo)(nil),      // 0: clusterpb.PeerInfo
	(*ReplyAddress)(nil),  // 1: clusterpb.ReplyAddress
	(*JoinCluster)(nil),   // 2: clusterpb.JoinCluster
	(*LeaveCluster)(nil),  // 3: clusterpb.LeaveCluster
	(*DiscoverPeers)(nil), // 4: clusterpb.DiscoverPeers
	(*PeerList)(nil),      // 5: clusterpb.PeerList
}
var file_cluster_cluster_proto_depIdxs = []int32{
	0, // 0: clusterpb.JoinCluster.self:type_name -> clusterpb.PeerInfo
	1, // 1: clusterpb.DiscoverPeers.reply_to:type_name -> clusterpb.ReplyAddress
	0, // 2: clusterpb.PeerList.peers:type_name -> clusterpb.PeerInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cluster_cluster_proto_init() }
func file_cluster_cluster_proto_init() {
	if File_cluster_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cluster_cluster_proto_rawDesc), len(file_cluster_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cluster_cluster_proto_goTypes,
		DependencyIndexes: file_cluster_cluster_proto_depIdxs,
		MessageInfos:      file_cluster_cluster_proto_msgTypes,
	}.Build()
	File_cluster_cluster_proto = out.File
	file_cluster_cluster_proto_goTypes = nil
	file_cluster_cluster_proto_depIdxs = nil
}
